package com.example.ui.screens

import androidx.activity.compose.BackHandler
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.ui.theme.TelegramBlue
import com.example.ui.theme.TelegramDeletedRed
import com.example.ui.theme.TelegramGhostCyan

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ArchitectureScreen(
    onBack: () -> Unit
) {
    BackHandler {
        onBack()
    }

    Scaffold(
        topBar = {
            TopAppBar(
                navigationIcon = {
                    IconButton(
                        onClick = onBack,
                        modifier = Modifier.testTag("arch_back_button")
                    ) {
                        Icon(
                            imageVector = Icons.AutoMirrored.Filled.ArrowBack,
                            contentDescription = "Back",
                            tint = Color.White
                        )
                    }
                },
                title = {
                    Column {
                        Text(
                            text = "Telegram Architecture & MTProto",
                            style = MaterialTheme.typography.titleMedium.copy(
                                fontWeight = FontWeight.Bold,
                                color = Color.White
                            )
                        )
                        Text(
                            text = "DrKLO vs TDLib Engine Pipelines",
                            style = MaterialTheme.typography.bodySmall.copy(
                                color = TelegramGhostCyan,
                                fontSize = 11.sp
                            )
                        )
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.surface
                )
            )
        }
    ) { innerPadding ->
        LazyColumn(
            modifier = Modifier
                .fillMaxSize()
                .padding(innerPadding)
                .background(MaterialTheme.colorScheme.background)
                .padding(14.dp)
                .testTag("architecture_screen_column"),
            verticalArrangement = Arrangement.spacedBy(14.dp)
        ) {
            // Section 1: Official DrKLO/Telegram vs TDLib comparison
            item {
                Card(
                    colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
                    shape = RoundedCornerShape(14.dp)
                ) {
                    Column(modifier = Modifier.padding(14.dp)) {
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Icon(Icons.Default.DeviceHub, contentDescription = null, tint = TelegramBlue)
                            Spacer(modifier = Modifier.width(8.dp))
                            Text(
                                text = "MTProto (DrKLO) vs TDLib Architecture",
                                style = MaterialTheme.typography.titleSmall.copy(
                                    fontWeight = FontWeight.Bold,
                                    color = Color.White
                                )
                            )
                        }

                        Spacer(modifier = Modifier.height(8.dp))

                        Text(
                            text = "Telegram Android (DrKLO/Telegram) does NOT use TDLib directly. Instead, it uses custom MTProto C++ native bindings (ConnectionsManager JNI) with Java-level TLObject serialization generated by scheme.tl.",
                            fontSize = 12.sp,
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                            lineHeight = 18.sp
                        )

                        Spacer(modifier = Modifier.height(10.dp))

                        ArchitectureFlowBox(
                            title = "DrKLO/Telegram Pipeline",
                            steps = listOf(
                                "UI View (ChatActivity / ChatMessageCell)",
                                "MessagesController (markDialogAsRead / sendTyping)",
                                "ConnectionsManager.java (sendRequestInternal)",
                                "JNI -> libtmessages.so (C++ MTProto Socket Engine)",
                                "Telegram Data Centers (DC1 - DC5)"
                            ),
                            accentColor = TelegramBlue
                        )

                        Spacer(modifier = Modifier.height(10.dp))

                        ArchitectureFlowBox(
                            title = "TDLib Pipeline (Third-Party Clients)",
                            steps = listOf(
                                "Custom Kotlin/Java App Controller",
                                "TDLib Client JSON / JNI Interface (td_api.SendChatAction)",
                                "libtdjson.so / C++ Actor System (td::actor)",
                                "Internal Encrypted SQLite (SqliteDb)",
                                "Telegram MTProto Gateway"
                            ),
                            accentColor = TelegramGhostCyan
                        )
                    }
                }
            }

            // Section 2: Anti-Delete SQLite Schema Migration
            item {
                Card(
                    colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
                    shape = RoundedCornerShape(14.dp)
                ) {
                    Column(modifier = Modifier.padding(14.dp)) {
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Icon(Icons.Default.Storage, contentDescription = null, tint = TelegramDeletedRed)
                            Spacer(modifier = Modifier.width(8.dp))
                            Text(
                                text = "SQLite Database & Anti-Delete Strategy",
                                style = MaterialTheme.typography.titleSmall.copy(
                                    fontWeight = FontWeight.Bold,
                                    color = Color.White
                                )
                            )
                        }

                        Spacer(modifier = Modifier.height(8.dp))

                        Text(
                            text = "Telegram stores messages locally in MessagesStorage.java using raw SQLiteDatabase. Normally, when a sender deletes a message, Telegram executes SQL DELETE queries.",
                            fontSize = 12.sp,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )

                        Spacer(modifier = Modifier.height(8.dp))

                        Surface(
                            color = Color(0xFF0F172A),
                            shape = RoundedCornerShape(8.dp),
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            Column(modifier = Modifier.padding(10.dp)) {
                                Text(
                                    text = "-- Step 1: Add is_deleted column in MessagesStorage.java",
                                    fontFamily = FontFamily.Monospace,
                                    fontSize = 11.sp,
                                    color = Color.Gray
                                )
                                Text(
                                    text = "ALTER TABLE messages ADD COLUMN is_deleted INTEGER DEFAULT 0;",
                                    fontFamily = FontFamily.Monospace,
                                    fontSize = 11.sp,
                                    color = TelegramGhostCyan
                                )
                                Spacer(modifier = Modifier.height(6.dp))
                                Text(
                                    text = "-- Step 2: In markMessagesAsDeleted(), mutate to UPDATE:",
                                    fontFamily = FontFamily.Monospace,
                                    fontSize = 11.sp,
                                    color = Color.Gray
                                )
                                Text(
                                    text = "UPDATE messages SET is_deleted = 1, edit_date = strftime('%s','now') WHERE mid IN (...);",
                                    fontFamily = FontFamily.Monospace,
                                    fontSize = 11.sp,
                                    color = TelegramDeletedRed
                                )
                            }
                        }

                        Spacer(modifier = Modifier.height(8.dp))

                        Text(
                            text = "Also preserve cached media files in cacheDir! Never purge media_v4 rows associated with deleted mids.",
                            fontSize = 11.sp,
                            color = Color(0xFFFBBF24)
                        )
                    }
                }
            }

            // Section 3: AyuGram Preference Architecture
            item {
                Card(
                    colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
                    shape = RoundedCornerShape(14.dp)
                ) {
                    Column(modifier = Modifier.padding(14.dp)) {
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Icon(Icons.Default.Security, contentDescription = null, tint = TelegramGhostCyan)
                            Spacer(modifier = Modifier.width(8.dp))
                            Text(
                                text = "Central Config: AyuConfig.java Pattern",
                                style = MaterialTheme.typography.titleSmall.copy(
                                    fontWeight = FontWeight.Bold,
                                    color = Color.White
                                )
                            )
                        }

                        Spacer(modifier = Modifier.height(8.dp))

                        Text(
                            text = "Create a dedicated class TMessagesProj/src/main/java/org/telegram/messenger/AyuConfig.java using Android SharedPreferences. This keeps privacy preferences decoupled from official Telegram preferences:",
                            fontSize = 12.sp,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )

                        Spacer(modifier = Modifier.height(8.dp))

                        Surface(
                            color = Color(0xFF0F172A),
                            shape = RoundedCornerShape(8.dp),
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            Text(
                                text = """
public class AyuConfig {
    public static boolean ghostMode = true;
    public static boolean hideTyping = true;
    public static boolean antiDelete = true;
    public static boolean ghostStories = true;
    
    public static void loadConfig(Context ctx) {
        SharedPreferences p = ctx.getSharedPreferences("ayugram_config", 0);
        ghostMode = p.getBoolean("ghostMode", true);
        hideTyping = p.getBoolean("hideTyping", true);
        antiDelete = p.getBoolean("antiDelete", true);
    }
}
                                """.trimIndent(),
                                fontFamily = FontFamily.Monospace,
                                fontSize = 11.sp,
                                color = Color(0xFF67E8F9),
                                modifier = Modifier.padding(10.dp)
                            )
                        }
                    }
                }
            }

            // Section 4: Compilation & Build Notes
            item {
                Card(
                    colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
                    shape = RoundedCornerShape(14.dp)
                ) {
                    Column(modifier = Modifier.padding(14.dp)) {
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Icon(Icons.Default.Build, contentDescription = null, tint = Color(0xFF10B981))
                            Spacer(modifier = Modifier.width(8.dp))
                            Text(
                                text = "Compiling DrKLO/Telegram (FOSS)",
                                style = MaterialTheme.typography.titleSmall.copy(
                                    fontWeight = FontWeight.Bold,
                                    color = Color.White
                                )
                            )
                        }

                        Spacer(modifier = Modifier.height(8.dp))

                        Text(
                            text = "1. Git Submodules: DrKLO/Telegram relies on submodules. Run:\n   git clone --recursive https://github.com/DrKLO/Telegram.git\n\n2. NDK Requirement: Use NDK r21e or r23c (matching gradle.properties ndkVersion).\n\n3. API Credentials: Get api_id & api_hash from my.telegram.org and declare them in TMessagesProj/src/main/java/org/telegram/messenger/BuildVars.java.\n\n4. Native Build: CMake builds libtmessages.so which bundles libtgvoip, ffmpeg, and boringSSL.",
                            fontSize = 12.sp,
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                            lineHeight = 18.sp
                        )
                    }
                }
            }

            item {
                Spacer(modifier = Modifier.height(24.dp))
            }
        }
    }
}

@Composable
fun ArchitectureFlowBox(title: String, steps: List<String>, accentColor: Color) {
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .border(1.dp, accentColor.copy(alpha = 0.4f), RoundedCornerShape(8.dp))
            .background(accentColor.copy(alpha = 0.05f))
            .padding(10.dp)
    ) {
        Text(
            text = title,
            fontWeight = FontWeight.Bold,
            fontSize = 12.sp,
            color = accentColor
        )
        Spacer(modifier = Modifier.height(6.dp))
        steps.forEachIndexed { index, step ->
            Row(verticalAlignment = Alignment.CenterVertically) {
                Text(
                    text = "${index + 1}. ",
                    fontWeight = FontWeight.Bold,
                    fontSize = 11.sp,
                    color = accentColor
                )
                Text(
                    text = step,
                    fontSize = 11.sp,
                    color = Color(0xFFE2E8F0),
                    fontFamily = FontFamily.Monospace
                )
            }
            if (index < steps.size - 1) {
                Spacer(modifier = Modifier.height(2.dp))
            }
        }
    }
}

